// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM7Gvzmbd3sgkQyR5ma6pXDCHOtsDUeqM',
    appId: '1:738313882005:web:4b4b09a5c0e1770279ce9c',
    messagingSenderId: '738313882005',
    projectId: 'form-validation-836f0',
    authDomain: 'form-validation-836f0.firebaseapp.com',
    storageBucket: 'form-validation-836f0.firebasestorage.app',
    measurementId: 'G-SFF6LW0L3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyPSfbLdOJ-HBH3dkXTUnbBUihKMRzl64',
    appId: '1:738313882005:android:3aaa68f1f8f2fc9779ce9c',
    messagingSenderId: '738313882005',
    projectId: 'form-validation-836f0',
    storageBucket: 'form-validation-836f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeLs2LFyyshlXQJYjEeeYsslTDFy2Vck8',
    appId: '1:738313882005:ios:fb1fc4532a295dc279ce9c',
    messagingSenderId: '738313882005',
    projectId: 'form-validation-836f0',
    storageBucket: 'form-validation-836f0.firebasestorage.app',
    iosBundleId: 'com.example.formValidation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeLs2LFyyshlXQJYjEeeYsslTDFy2Vck8',
    appId: '1:738313882005:ios:fb1fc4532a295dc279ce9c',
    messagingSenderId: '738313882005',
    projectId: 'form-validation-836f0',
    storageBucket: 'form-validation-836f0.firebasestorage.app',
    iosBundleId: 'com.example.formValidation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM7Gvzmbd3sgkQyR5ma6pXDCHOtsDUeqM',
    appId: '1:738313882005:web:4e994ebc4e18207079ce9c',
    messagingSenderId: '738313882005',
    projectId: 'form-validation-836f0',
    authDomain: 'form-validation-836f0.firebaseapp.com',
    storageBucket: 'form-validation-836f0.firebasestorage.app',
    measurementId: 'G-15P9Z400X1',
  );
}
